flags:
  git-annex:
    production: true
    assistant: true
    pairing: true
    s3: true
    webdav: true
    torrentparser: true
    webapp: true
    magicmime: false
    dbus: false
    debuglocks: false
packages:
- '.'
extra-deps:
- aws-0.17.1
- bloomfilter-2.0.1.0
- torrent-10000.1.1
explicit-setup-deps:
  git-annex: true
resolver: lts-9.9
