flags:
  git-annex:
    concurrentoutput: true
    production: true
    assistant: true
    pairing: true
    network-uri: true
    s3: true
    webdav: true
    torrentparser: true
    webapp: true
    magicmime: false
    dbus: false
    android: false
    androidsplice: false
packages:
- '.'
extra-deps:
- IfElse-0.85
- aws-0.20
- bloomfilter-2.0.1.0
- esqueleto-2.5.3
- sandi-0.4.2
- torrent-10000.1.1
- persistent-2.7.3.1
- conduit-1.3.0.2
- resourcet-1.2.1
allow-newer: true
explicit-setup-deps:
  git-annex: true
resolver: lts-11.11
