flags:
  git-annex:
    concurrentoutput: true
    production: true
    assistant: true
    pairing: true
    cryptonite: true
    network-uri: true
    s3: true
    testsuite: true
    webdav: true
    torrentparser: true
    webapp: true
    magicmime: false
    android: false
    androidsplice: false
    ekg: false
packages:
- '.'
resolver: lts-5.0
