flags:
  git-annex:
    concurrentoutput: true
    tahoe: true
    tdfa: true
    feed: true
    webapp-secure: true
    production: true
    assistant: true
    pairing: true
    cryptonite: true
    network-uri: true
    s3: true
    testsuite: true
    webdav: true
    torrentparser: true
    quvi: true
    dns: true
    webapp: true
    android: false
    androidsplice: false
    ekg: false
packages:
- '.'
resolver: lts-5.0
