flags:
  git-annex:
    concurrentoutput: true
    production: true
    assistant: true
    pairing: true
    cryptonite: true
    network-uri: true
    s3: true
    testsuite: true
    webdav: true
    torrentparser: true
    webapp: true
    magicmime: false
    dbus: false
    android: false
    androidsplice: false
packages:
- '.'
extra-deps:
- esqueleto-2.5.1
- yesod-default-1.2.0
explicit-setup-deps:
  git-annex: true
resolver: lts-7.18
