flags:
  git-annex:
    concurrentoutput: false
    tahoe: true
    tdfa: true
    inotify: true
    feed: true
    webapp-secure: true
    production: true
    ekg: false
    assistant: true
    pairing: true
    cryptonite: true
    xmpp: false
    network-uri: true
    s3: true
    dbus: false
    testsuite: true
    webdav: true
    torrentparser: true
    android: false
    androidsplice: false
    quvi: true
    dns: true
    desktopnotify: true
    webapp: true
packages:
- '.'
extra-deps:
- Win32-extras-0.2.0.1
resolver: nightly-2015-12-28
